name: Main CI Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        version: [ 16 ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        name: Use Node.js ${{ matrix.version }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: yarn install

      - name: Type Check
        run: yarn tsc

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
